version = 0.1
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::730335421807:user/aws-sam-cli-managed-dev-pipeline-resou-PipelineUser-Wr0DhgD0LkFv"
permissions_provider = "AWS IAM"

[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::730335421807:role/aws-sam-cli-managed-dev-pipel-PipelineExecutionRole-WiGwB03lEeSh"
cloudformation_execution_role = "arn:aws:iam::730335421807:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionRo-ilSdtq7aUAl2"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-r-artifactsbucket-ewpprsb4o5zc"
image_repository = ""
region = "us-east-1"

[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::730335421807:role/aws-sam-cli-managed-prod-pipe-PipelineExecutionRole-j35GBnzyxlTU"
cloudformation_execution_role = "arn:aws:iam::730335421807:role/aws-sam-cli-managed-prod--CloudFormationExecutionRo-ljRn39hTcK4Q"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline--artifactsbucket-ybseukz2ehqr"
image_repository = ""
region = "us-east-1"
